/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-12-31 16:40:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Project.connectionprovider;
import java.sql.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1703224877179L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1704021962334L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Project.connectionprovider");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/home-style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src='https://kit.fontawesome.com/a076d05399.js'></script>\r\n");
      out.write("</head>\r\n");
      out.write("    <!--Header-->\r\n");
      out.write("    <br>\r\n");
      out.write("    <div class=\"topnav sticky\">\r\n");
      out.write("  ");
String email=session.getAttribute("email").toString(); 
      out.write("  \r\n");
      out.write("            <center><h2>Green supermarket</h2></center>\r\n");
      out.write("            <h2><a href=\"\">");
out.println(email); 
      out.write(" <i class='fas fa-user-alt'></i></a></h2>\r\n");
      out.write("            <a href=\"home.jsp\">Home<i class=\"fa fa-institution\"></i></a>\r\n");
      out.write("            <a href=\"myCart.jsp\">My Cart<i class='fas fa-cart-arrow-down'></i></a>\r\n");
      out.write("            <a href=\"myOrders.jsp\">My Orders  <i class='fab fa-elementor'></i></a>\r\n");
      out.write("            <a href=\"changeDetails.jsp\">Change Details <i class=\"fa fa-edit\"></i></a>\r\n");
      out.write("            <a href=\"messageUs.jsp\">Message Us <i class='fas fa-comment-alt'></i></a>\r\n");
      out.write("            <a href=\"about.jsp\">About <i class=\"fa fa-address-book\"></i></a>\r\n");
      out.write("            <a href=\"logout.jsp\">Logout <i class='fas fa-share-square'></i></a>\r\n");
      out.write("            <div class=\"search-container\">\r\n");
      out.write("            <form action=\"searchHome.jsp\" method=\"post\">\r\n");
      out.write("            <input type=\"text\" Placeholder=\"search\" name=\"search\" >\r\n");
      out.write("            <button type=\"submit\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("            </form>\r\n");
      out.write("           </div>\r\n");
      out.write("          </div>\r\n");
      out.write("           <br>\r\n");
      out.write("           <!--table-->\r\n");
      out.write('\r');
      out.write('\n');
      out.write(" <div class=\"footer\">\r\n");
      out.write("          <p>All Right Reserved @ Ashen Gayathra</p>\r\n");
      out.write("      </div>");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("  <title>Home</title>\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: #3CBC8D;\r\n");
      out.write("      font-family: \"Open Sans\", sans-serif;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h3 {\r\n");
      out.write("      color: yellow;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table {\r\n");
      out.write("      border: 1px solid #ccc;\r\n");
      out.write("      border-collapse: collapse;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      margin-left: 5%;\r\n");
      out.write("      table-layout: fixed;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table caption {\r\n");
      out.write("      font-size: 1.5em;\r\n");
      out.write("      margin: .5em 0 .75em;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table tr {\r\n");
      out.write("      background-color: #f8f8f8;\r\n");
      out.write("      border: 1px solid #ddd;\r\n");
      out.write("      padding: .35em;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table th,\r\n");
      out.write("    table td {\r\n");
      out.write("      padding: .625em;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table th {\r\n");
      out.write("      font-size: .85em;\r\n");
      out.write("      letter-spacing: .1em;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media screen and (max-width: 600px) {\r\n");
      out.write("      table {\r\n");
      out.write("        border: 0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      table caption {\r\n");
      out.write("        font-size: 1.3em;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      table thead {\r\n");
      out.write("        border: none;\r\n");
      out.write("        clip: rect(0 0 0 0);\r\n");
      out.write("        height: 1px;\r\n");
      out.write("        margin: -1px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 1px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      table tr {\r\n");
      out.write("        border-bottom: 3px solid #ddd;\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: .625em;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      table td {\r\n");
      out.write("        border-bottom: 1px solid #ddd;\r\n");
      out.write("        display: block;\r\n");
      out.write("        font-size: .8em;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      table td::before {\r\n");
      out.write("        content: attr(data-label);\r\n");
      out.write("        float: left;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      table td:last-child {\r\n");
      out.write("        border-bottom: 0;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <div style=\"color: white; text-align: center; font-size: 30px;\">Home <i class=\"fa fa-institution\"></i></div>\r\n");
      out.write("  ");

  String msg=request.getParameter("msg");
  if("added".equals(msg))
  {
  
      out.write("\r\n");
      out.write("  <h3 class=\"alert\">Product added successfully!</h3>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("  ");

  if("exist".equals(msg))
  {
  
      out.write("\r\n");
      out.write("  <h3 class=\"alert\">Product already exists in your cart! Quantity increased!</h3>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("  ");

  if("invalid".equals(msg))
  {
  
      out.write("\r\n");
      out.write("  <h3 class=\"alert\">Something went wrong! Try Again! </h3>\r\n");
      out.write("  ");
} 
      out.write("\r\n");
      out.write("  <table>\r\n");
      out.write("    <thead>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th scope=\"col\">ID</th>\r\n");
      out.write("        <th scope=\"col\">Name</th>\r\n");
      out.write("        <th scope=\"col\">Category</th>\r\n");
      out.write("        <th scope=\"col\"><i class=\"fa fa-inr\"></i> Price</th>\r\n");
      out.write("        <th scope=\"col\">Add to cart <i class='fas fa-cart-plus'></i></th>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write("      ");

      try{
        Connection con = connectionprovider.getCon();
        Statement st=con.createStatement();
        ResultSet rs = st.executeQuery("select *from product where active='Yes'");
        while(rs.next())
        {
      
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>");
      out.print(rs.getString(1) );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("        <td><i class=\"fa fa-inr\"></i> ");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("        <td><a href=\"addToCartAction.jsp?id=");
      out.print(rs.getString(1) );
      out.write("\">Add to cart <i class='fas fa-cart-plus'></i></a></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");

      }
      }
      catch(Exception e)
      {
      System.out.println(e);	
      }
      
      out.write("\r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
